[package]
name = "notify_push"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
redis = { version = "0.20", features = ["tokio-comp", "aio", "cluster"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
warp = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "signal"] }
futures = "0.3"
log = "0.4"
sqlx = { version = "0.5", features = ["runtime-tokio-rustls", "any", "macros", "mysql", "sqlite", "postgres"] }
dotenv = "0.15"
dashmap = "4"
once_cell = "1"
color-eyre = "0.5"
smallvec = "1"
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json"] }
warp-real-ip = "0.2"
parse-display = "0.5"
percent-encoding = "2"
rand = "0.8"
ahash = "0.7"
flexi_logger = { version = "0.18", features = ["colors"] }
tokio-stream = { version = "0.1", features = ["net"] }
structopt = "0.3"
derivative = "2"
nextcloud-config-parser = { version = "0.2", features = ["db-sqlx", "redis-connect"] }

[dev-dependencies]
mini-redis = "0.4"
tokio-tungstenite = "0.14"
http-auth-basic = "0.1"
test_client = { path = "test_client" }

[build-dependencies]
nextcloud_appinfo = "0.6"

[profile.dev.package.backtrace]
opt-level = 3

[profile.release]
lto = true

[features]
default = ["span-colors"]
span-colors = ["nextcloud-config-parser/span-colors"]

[workspace]