[package]
name = "test_client"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
tungstenite = { version = "0.13", default-features = false, features = ["rustls-tls"] }
color-eyre = "0.5"
serde_json = "1"
ureq = "2"
flexi_logger = { version = "0.18", features = ["colors"] }
log = "0.4"
base64 = "0.13"