name: Publish Docker image
on:
  push:
  
jobs:
  push_to_registry:
    name: Build and push nextcloud docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out my own repo
        uses: actions/checkout@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/pestotoast/mmx-node
          tags: |
            type=raw,value=latest
            type=semver,pattern={{raw}}

      - name: Push my own image to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          platforms: linux/amd64, linux/arm64, linux/arm/v7

