name: Release

on:
  release:
    types: [created]

env:
  APP_NAME: notify_push

jobs:
  release-binaries:
    name: Build release binaries
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - i686-unknown-linux-musl
          - armv7-unknown-linux-musleabihf
          - aarch64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.target }}
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/${{ matrix.target }}/release/notify_push
          asset_name: notify_push-${{ matrix.target }}
          tag: ${{ github.ref }}

  package:
    name: Package release
    runs-on: ubuntu-20.04
    steps:
      - name: musl-tools
        run: |
          sudo apt-get install musl-tools
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          target: x86_64-unknown-linux-musl
      - name: cross
        run: |
          cargo install cross
      - name: Setup krankler
        run: |
          wget https://github.com/ChristophWurst/krankerl/releases/download/v0.13.0/krankerl
          chmod +x krankerl
      - name: Package app
        run: |
          ./krankerl package
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/artifacts/${{ env.APP_NAME }}.tar.gz
          asset_name: ${{ env.APP_NAME }}.tar.gz
          tag: ${{ github.ref }}